// 由 scripts/gen-guide-strings.py 从 iOS App 文案生成，不要手改。
// App 文案改了按钮名，重新跑一次脚本即可同步。
import type { Locale } from "@/i18n/messages";

export const APP_STRINGS: Record<Locale, Record<string, string>> = {
  "zh": {
    "active.header.end": "结束训练",
    "active.rest.skip": "跳过休息",
    "active.rest.title": "组间休息",
    "adjust.adoptAdjusted": "采用调整版",
    "adjust.continueChat": "继续和 AI 讨论",
    "adjust.useOriginal": "使用原版",
    "ai.error.noNetwork": "没有网络连接",
    "ai.history.title": "聊天记录",
    "ai.tier.flash": "日常",
    "ai.tier.professional": "深度",
    "ai.version.classic": "经典版",
    "ai.version.immersive": "新版（沉浸）",
    "baseline.status.learning": "基线学习中，评分会越来越贴合你的身体",
    "bump.choice.receive": "接收朋友的计划",
    "bump.choice.send": "分享给朋友",
    "bump.error.startFailed": "无法启动近场服务，请检查权限设置",
    "bump.verify.confirm": "一致",
    "bump.verify.title": "安全验证",
    "camera.permission.denied.settings": "前往设置",
    "camera.permission.denied.title": "需要相机权限",
    "chat.menu.album": "相册",
    "chat.menu.camera": "拍照",
    "chat.menu.sharePlan": "训练计划",
    "chat.menu.voice": "语音",
    "coach.title": "AI 实时教练",
    "common.next": "下一步",
    "cycle.profile.healthKitAuth": "HealthKit 授权",
    "cycle.reminder.enableLabel": "开启提醒",
    "cycle.tab.calories": "热量",
    "cycle.weeklyReport.aiTitle": "AI 智能总结",
    "cycle.weeklyReport.comparisonTitle": "训练对比",
    "cycle.weeklyReport.localNoData": "暂无训练数据可分析",
    "cycle.weeklyReport.overviewTitle": "本轮概览",
    "cycle.weeklyReport.stateChartTitle": "每次训练回顾",
    "decision.daily.newDay": "🌅 新的一天",
    "decision.planCard.recommended": "推荐",
    "decision.postWorkout.diaryLabel": "训练日记",
    "decision.postWorkout.saveRecord": "保存记录",
    "decision.readiness.todayAdvice": "今日训练建议",
    "food.add.title": "添加食物记录",
    "food.mode.aiPhoto": "AI Photo",
    "food.mode.manual": "自己填",
    "food.photo.album": "相册",
    "food.photo.take": "拍照",
    "health.mode.connectApple": "连接 Apple Health",
    "health.mode.manual": "我没有智能手表",
    "health.mode.skip": "跳过，仅使用自评",
    "health.mode.title": "健康数据来源",
    "home.watch.disconnected": "连接 Apple Watch",
    "home.weekly.title": "本周训练",
    "home.weeklyReport.title": "AI 周报",
    "immersive.suggest.progress": "分析我的训练进度",
    "immersive.suggest.training": "帮我制定训练计划",
    "manual.input.done": "记录完成",
    "planHub.bump.title": "碰一碰",
    "planHub.import.section": "截图导入",
    "planHub.shareCard.title": "分享卡片",
    "planHub.title": "计划工具",
    "profile.aiMode.functional": "功能训练",
    "profile.aiMode.title": "AI 训练模式",
    "share.plan.shareAction": "分享计划",
    "smartPlan.card.title": "AI 智能生成计划",
    "smartPlan.error.failed": "网络请求失败，请检查网络后重试",
    "smartPlan.importAll": "全部导入",
    "sub.title": "订阅管理",
    "tab.ai": "AI",
    "tab.cycle": "周期",
    "tab.home": "主页",
    "tab.profile": "我的",
    "tab.training": "训练",
    "training.create.combo": "组合训练",
    "training.create.customCombo": "自由组合",
    "training.create.singlePart": "单部位训练",
    "training.empty.create": "创建计划",
    "training.header.add": "新增",
    "training.plan.start": "开始训练",
    "voice.permission.denied": "需要语音识别权限",
    "workout.category.functional": "功能性训练",
    "workout.category.strength": "力量训练"
  },
  "zh-Hant": {
    "active.header.end": "結束訓練",
    "active.rest.skip": "跳過休息",
    "active.rest.title": "組間休息",
    "adjust.adoptAdjusted": "採用調整版",
    "adjust.continueChat": "繼續同 AI 傾",
    "adjust.useOriginal": "用原版",
    "ai.error.noNetwork": "冇網絡連接",
    "ai.history.title": "聊天紀錄",
    "ai.tier.flash": "日常",
    "ai.tier.professional": "深度",
    "ai.version.classic": "經典版",
    "ai.version.immersive": "新版（沉浸）",
    "baseline.status.learning": "基線學習緊，評分會越嚟越貼合你嘅身體",
    "bump.choice.receive": "接收朋友嘅計劃",
    "bump.choice.send": "分享俾朋友",
    "bump.error.startFailed": "無法啟動近場服務，請檢查權限設置",
    "bump.verify.confirm": "一致",
    "bump.verify.title": "安全驗證",
    "camera.permission.denied.settings": "前往設定",
    "camera.permission.denied.title": "需要相機權限",
    "chat.menu.album": "相簿",
    "chat.menu.camera": "影相",
    "chat.menu.sharePlan": "訓練計劃",
    "chat.menu.voice": "語音",
    "coach.title": "AI 即時教練",
    "common.next": "下一步",
    "cycle.profile.healthKitAuth": "HealthKit 授權",
    "cycle.reminder.enableLabel": "開啟提醒",
    "cycle.tab.calories": "熱量",
    "cycle.weeklyReport.aiTitle": "AI 智能總結",
    "cycle.weeklyReport.comparisonTitle": "訓練對比",
    "cycle.weeklyReport.localNoData": "暫無訓練數據可分析",
    "cycle.weeklyReport.overviewTitle": "本輪概覽",
    "cycle.weeklyReport.stateChartTitle": "每次訓練回顧",
    "decision.daily.newDay": "🌅 新嘅一日",
    "decision.planCard.recommended": "推薦",
    "decision.postWorkout.diaryLabel": "訓練日記",
    "decision.postWorkout.saveRecord": "儲存紀錄",
    "decision.readiness.todayAdvice": "今日訓練建議",
    "food.add.title": "添加食物紀錄",
    "food.mode.aiPhoto": "AI Photo",
    "food.mode.manual": "自己填",
    "food.photo.album": "相簿",
    "food.photo.take": "影相",
    "health.mode.connectApple": "連接 Apple Health",
    "health.mode.manual": "我冇智能手錶",
    "health.mode.skip": "跳過，僅使用自評",
    "health.mode.title": "健康數據來源",
    "home.watch.disconnected": "連接 Apple Watch",
    "home.weekly.title": "本週訓練",
    "home.weeklyReport.title": "AI 週報",
    "immersive.suggest.progress": "分析我嘅訓練進度",
    "immersive.suggest.training": "幫我制定訓練計劃",
    "manual.input.done": "記錄完成",
    "planHub.bump.title": "碰一碰",
    "planHub.import.section": "截圖導入",
    "planHub.shareCard.title": "分享卡片",
    "planHub.title": "計劃工具",
    "profile.aiMode.functional": "功能訓練",
    "profile.aiMode.title": "AI 訓練模式",
    "share.plan.shareAction": "分享計劃",
    "smartPlan.card.title": "AI 智能生成計劃",
    "smartPlan.error.failed": "網絡請求失敗，請檢查網絡後重試",
    "smartPlan.importAll": "全部導入",
    "sub.title": "訂閱管理",
    "tab.ai": "AI",
    "tab.cycle": "週期",
    "tab.home": "主頁",
    "tab.profile": "我的",
    "tab.training": "訓練",
    "training.create.combo": "組合訓練",
    "training.create.customCombo": "自由組合",
    "training.create.singlePart": "單部位訓練",
    "training.empty.create": "建立計劃",
    "training.header.add": "新增",
    "training.plan.start": "開始訓練",
    "voice.permission.denied": "需要語音識別權限",
    "workout.category.functional": "功能性訓練",
    "workout.category.strength": "力量訓練"
  },
  "en": {
    "active.header.end": "End Training",
    "active.rest.skip": "Skip Rest",
    "active.rest.title": "Rest Between Sets",
    "adjust.adoptAdjusted": "Adopt Adjusted",
    "adjust.continueChat": "Discuss with AI",
    "adjust.useOriginal": "Use Original",
    "ai.error.noNetwork": "No network connection",
    "ai.history.title": "Chat History",
    "ai.tier.flash": "Flash",
    "ai.tier.professional": "Deep",
    "ai.version.classic": "Classic",
    "ai.version.immersive": "New (Immersive)",
    "baseline.status.learning": "Baseline is learning, scoring will fit your body better over time",
    "bump.choice.receive": "Receive from Friend",
    "bump.choice.send": "Share with Friend",
    "bump.error.startFailed": "Cannot start nearby service, check permissions",
    "bump.verify.confirm": "Match",
    "bump.verify.title": "Security Verification",
    "camera.permission.denied.settings": "Open Settings",
    "camera.permission.denied.title": "Camera Access Required",
    "chat.menu.album": "Album",
    "chat.menu.camera": "Camera",
    "chat.menu.sharePlan": "Plan",
    "chat.menu.voice": "Voice",
    "coach.title": "AI Coach",
    "common.next": "Next",
    "cycle.profile.healthKitAuth": "HealthKit Authorization",
    "cycle.reminder.enableLabel": "Enable Reminder",
    "cycle.tab.calories": "Calories",
    "cycle.weeklyReport.aiTitle": "AI Smart Summary",
    "cycle.weeklyReport.comparisonTitle": "Training Comparison",
    "cycle.weeklyReport.localNoData": "No training data to analyze yet",
    "cycle.weeklyReport.overviewTitle": "Cycle Overview",
    "cycle.weeklyReport.stateChartTitle": "Training Session Review",
    "decision.daily.newDay": "🌅 New Day",
    "decision.planCard.recommended": "Recommended",
    "decision.postWorkout.diaryLabel": "Training Diary",
    "decision.postWorkout.saveRecord": "Save Record",
    "decision.readiness.todayAdvice": "Today's Training Advice",
    "food.add.title": "Add Food Record",
    "food.mode.aiPhoto": "AI Photo",
    "food.mode.manual": "Manual",
    "food.photo.album": "Album",
    "food.photo.take": "Camera",
    "health.mode.connectApple": "Connect Apple Health",
    "health.mode.manual": "I don't have a smartwatch",
    "health.mode.skip": "Skip, use self-assessment only",
    "health.mode.title": "Health Data Source",
    "home.watch.disconnected": "Connect Apple Watch",
    "home.weekly.title": "This Week's Training",
    "home.weeklyReport.title": "AI Weekly Report",
    "immersive.suggest.progress": "Analyze my progress",
    "immersive.suggest.training": "Create a training plan",
    "manual.input.done": "Done",
    "planHub.bump.title": "WShare",
    "planHub.import.section": "Import from Screenshot",
    "planHub.shareCard.title": "Share Card",
    "planHub.title": "Plan Tools",
    "profile.aiMode.functional": "Functional",
    "profile.aiMode.title": "AI Training Mode",
    "share.plan.shareAction": "Share Plan",
    "smartPlan.card.title": "AI Smart Plan Generator",
    "smartPlan.error.failed": "Network error, please check and retry",
    "smartPlan.importAll": "Import All",
    "sub.title": "Subscription",
    "tab.ai": "AI",
    "tab.cycle": "Cycle",
    "tab.home": "Home",
    "tab.profile": "Me",
    "tab.training": "Training",
    "training.create.combo": "Combo Training",
    "training.create.customCombo": "Free Combo",
    "training.create.singlePart": "Single Muscle Group",
    "training.empty.create": "Create Plan",
    "training.header.add": "Add",
    "training.plan.start": "Start Training",
    "voice.permission.denied": "Speech recognition permission required",
    "workout.category.functional": "Functional Training",
    "workout.category.strength": "Strength Training"
  },
  "ja": {
    "active.header.end": "トレーニング終了",
    "active.rest.skip": "休憩をスキップ",
    "active.rest.title": "セット間の休憩",
    "adjust.adoptAdjusted": "調整版を採用",
    "adjust.continueChat": "AIと相談を続ける",
    "adjust.useOriginal": "オリジナルを使用",
    "ai.error.noNetwork": "ネットワーク接続がありません",
    "ai.history.title": "会話履歴",
    "ai.tier.flash": "通常",
    "ai.tier.professional": "深考",
    "ai.version.classic": "クラシック",
    "ai.version.immersive": "新版（イマーシブ）",
    "baseline.status.learning": "ベースラインを学習中です。評価はだんだんあなたの身体に合っていきます",
    "bump.choice.receive": "友達から受信",
    "bump.choice.send": "友達にシェア",
    "bump.error.startFailed": "近接サービスを開始できません。権限を確認してください",
    "bump.verify.confirm": "一致",
    "bump.verify.title": "セキュリティ確認",
    "camera.permission.denied.settings": "設定を開く",
    "camera.permission.denied.title": "カメラへのアクセスが必要です",
    "chat.menu.album": "アルバム",
    "chat.menu.camera": "カメラ",
    "chat.menu.sharePlan": "プラン",
    "chat.menu.voice": "音声",
    "coach.title": "AIリアルタイムコーチ",
    "common.next": "次へ",
    "cycle.profile.healthKitAuth": "HealthKit権限",
    "cycle.reminder.enableLabel": "リマインダーを有効化",
    "cycle.tab.calories": "カロリー",
    "cycle.weeklyReport.aiTitle": "AIスマートサマリー",
    "cycle.weeklyReport.comparisonTitle": "トレーニング比較",
    "cycle.weeklyReport.localNoData": "まだ分析するトレーニングデータがありません",
    "cycle.weeklyReport.overviewTitle": "サイクル概要",
    "cycle.weeklyReport.stateChartTitle": "トレーニングセッションレビュー",
    "decision.daily.newDay": "🌅 新しい一日",
    "decision.planCard.recommended": "おすすめ",
    "decision.postWorkout.diaryLabel": "トレーニング日記",
    "decision.postWorkout.saveRecord": "記録を保存",
    "decision.readiness.todayAdvice": "今日のトレーニングアドバイス",
    "food.add.title": "食事記録を追加",
    "food.mode.aiPhoto": "AI撮影",
    "food.mode.manual": "手動入力",
    "food.photo.album": "アルバム",
    "food.photo.take": "撮影",
    "health.mode.connectApple": "Apple Healthに接続",
    "health.mode.manual": "スマートウォッチを持っていません",
    "health.mode.skip": "スキップ、自己評価のみ使用",
    "health.mode.title": "健康データソース",
    "home.watch.disconnected": "Apple Watchを接続する",
    "home.weekly.title": "今週のトレーニング",
    "home.weeklyReport.title": "AI週間レポート",
    "immersive.suggest.progress": "進捗を分析",
    "immersive.suggest.training": "トレーニングプランを作成",
    "manual.input.done": "記録完了",
    "planHub.bump.title": "WShare",
    "planHub.import.section": "スクリーンショットから取込",
    "planHub.shareCard.title": "シェアカード",
    "planHub.title": "プランツール",
    "profile.aiMode.functional": "ファンクショナル",
    "profile.aiMode.title": "AIトレーニングモード",
    "share.plan.shareAction": "プランをシェア",
    "smartPlan.card.title": "AIスマートプラン生成",
    "smartPlan.error.failed": "ネットワークエラー。接続を確認してください",
    "smartPlan.importAll": "すべてインポート",
    "sub.title": "サブスクリプション",
    "tab.ai": "AI",
    "tab.cycle": "サイクル",
    "tab.home": "ホーム",
    "tab.profile": "マイページ",
    "tab.training": "トレーニング",
    "training.create.combo": "複合トレーニング",
    "training.create.customCombo": "フリーコンボ",
    "training.create.singlePart": "単一部位",
    "training.empty.create": "プランを作成",
    "training.header.add": "追加",
    "training.plan.start": "トレーニング開始",
    "voice.permission.denied": "音声認識の許可が必要です",
    "workout.category.functional": "ファンクショナルトレーニング",
    "workout.category.strength": "筋力トレーニング"
  },
  "ko": {
    "active.header.end": "운동 종료",
    "active.rest.skip": "휴식 건너뛰기",
    "active.rest.title": "세트 간 휴식",
    "adjust.adoptAdjusted": "조정본 채택",
    "adjust.continueChat": "AI와 계속 상담",
    "adjust.useOriginal": "원본 사용",
    "ai.error.noNetwork": "네트워크 연결이 없어요",
    "ai.history.title": "대화 기록",
    "ai.tier.flash": "일상",
    "ai.tier.professional": "심층",
    "ai.version.classic": "클래식",
    "ai.version.immersive": "새 버전 (몰입)",
    "baseline.status.learning": "기준선을 학습 중이에요. 평가가 점점 당신의 몸에 맞춰져요",
    "bump.choice.receive": "친구에게서 수신",
    "bump.choice.send": "친구에게 공유",
    "bump.error.startFailed": "근거리 서비스를 시작할 수 없습니다. 권한을 확인하세요",
    "bump.verify.confirm": "일치",
    "bump.verify.title": "보안 인증",
    "camera.permission.denied.settings": "설정 열기",
    "camera.permission.denied.title": "카메라 접근 필요",
    "chat.menu.album": "앨범",
    "chat.menu.camera": "카메라",
    "chat.menu.sharePlan": "플랜",
    "chat.menu.voice": "음성",
    "coach.title": "AI 실시간 코치",
    "common.next": "다음",
    "cycle.profile.healthKitAuth": "HealthKit 권한",
    "cycle.reminder.enableLabel": "알림 활성화",
    "cycle.tab.calories": "칼로리",
    "cycle.weeklyReport.aiTitle": "AI 스마트 요약",
    "cycle.weeklyReport.comparisonTitle": "운동 비교",
    "cycle.weeklyReport.localNoData": "아직 분석할 운동 데이터가 없어요",
    "cycle.weeklyReport.overviewTitle": "주기 개요",
    "cycle.weeklyReport.stateChartTitle": "운동 세션 리뷰",
    "decision.daily.newDay": "🌅 새로운 하루",
    "decision.planCard.recommended": "추천",
    "decision.postWorkout.diaryLabel": "트레이닝 일기",
    "decision.postWorkout.saveRecord": "기록 저장",
    "decision.readiness.todayAdvice": "오늘의 운동 조언",
    "food.add.title": "식단 기록 추가",
    "food.mode.aiPhoto": "AI 촬영",
    "food.mode.manual": "직접 입력",
    "food.photo.album": "앨범",
    "food.photo.take": "촬영",
    "health.mode.connectApple": "Apple Health 연결",
    "health.mode.manual": "스마트워치가 없어요",
    "health.mode.skip": "건너뛰기, 자가평가만 사용",
    "health.mode.title": "건강 데이터 소스",
    "home.watch.disconnected": "Apple Watch 연결하기",
    "home.weekly.title": "이번 주 운동",
    "home.weeklyReport.title": "AI 주간 리포트",
    "immersive.suggest.progress": "내 진행 상황 분석",
    "immersive.suggest.training": "운동 플랜 만들기",
    "manual.input.done": "기록 완료",
    "planHub.bump.title": "WShare",
    "planHub.import.section": "스크린샷에서 가져오기",
    "planHub.shareCard.title": "공유 카드",
    "planHub.title": "플랜 도구",
    "profile.aiMode.functional": "기능성 운동",
    "profile.aiMode.title": "AI 트레이닝 모드",
    "share.plan.shareAction": "플랜 공유",
    "smartPlan.card.title": "AI 스마트 플랜 생성",
    "smartPlan.error.failed": "네트워크 오류. 연결을 확인해주세요",
    "smartPlan.importAll": "전체 가져오기",
    "sub.title": "구독 관리",
    "tab.ai": "AI",
    "tab.cycle": "주기",
    "tab.home": "홈",
    "tab.profile": "내 정보",
    "tab.training": "운동",
    "training.create.combo": "복합 운동",
    "training.create.customCombo": "자유 조합",
    "training.create.singlePart": "단일 부위",
    "training.empty.create": "계획 만들기",
    "training.header.add": "추가",
    "training.plan.start": "운동 시작",
    "voice.permission.denied": "음성 인식 권한이 필요해요",
    "workout.category.functional": "기능성 훈련",
    "workout.category.strength": "근력 운동"
  }
};
